name: simple-build
on: [push]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: obtain node (npm) and install dependencies
        uses: actions/setup-node@v1
        run: npm install

      - name: build site
        run: npm run build

      - name: deploy site
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'